@TaskManagerPro_HostAddress = http://localhost:5179


###
POST {{TaskManagerPro_HostAddress}}/taskManagerPro/Task
Content-Type: application/json

{
  "title": "Aprender Arquitectura Hexagonal",
  "description": "Terminar el backend con Francisco de IA",
  "userId": 1
}
###
GET {{TaskManagerPro_HostAddress}}/taskManagerPro/Task/1
